######################################################################
# Automatically generated by qmake (3.1) Tue Nov 26 16:18:26 2024
######################################################################


QT += core gui widgets network
CONFIG += c++11
SOURCES += main.cpp
HEADERS += 
FORMS +=
